### PR TITLE
Directional flow preference in IGM, demonstrated by Ed Bueler's C (2005) dome benchmark with time evolving smb

### PR DESCRIPTION
**Pull request by alexjarosch**
Dear Guillaume and colleagues,

as IGM grows and is used more widely in the community, I thought I do some benchmarking on the current version. First, let me say that I really appreciate your efforts on creating and maintaining IGM based on CNNs, great work!
However as AI is always tricky, it is good practice to benchmark such models as much as we can. I saw with appreciation that IGM includes tests and examples which get people going, but I missed an exact benchmark on the forward flow model part. So I thought I add one and share it with you.

Based on Ed Bueler's work on SIA flow model benchmarks from 2005:

**Bueler E**, Lingle CS, Kallen-Brown JA, Covey DN, Bowman LN. Exact solutions and verification of numerical models for isothermal ice sheets. _Journal of Glaciology_. 2005;51(173):291-306. doi:[10.3189/172756505781829449 ](https://doi.org/10.3189/172756505781829449)

I have added the Bueler C test (Table 2, p. 297 in his paper) as an example to IGM to see if IGM would grow a circular ice sheet, driven by circular symmetric, time evolving surface mass balance. That benchmark would run for a very long time (about 15000 years) but we already see issues in the first 1000 years. So I thought I stop there and submit the code.
The setup used here is based on the EISMINT I experiment parameters, which mostly are also used in IGM. I just set the sliding coeff to 0 (to avoid sliding) and A = 100 [MPa^-3 years^-1] coming from the A = 1x10^-16 [Pa^-3 years^-1] used in EISMINT, in Ed's work and in my numerical reference surface from a SIA model.

The numerical reference SIA surface is created with a mass conserving SIA model:
**Jarosch, A. H.**, Schoof, C. G., and Anslow, F. S.: Restoring mass conservation to shallow ice flow models over complex terrain, _The Cryosphere_, 7, 229–240, doi:[10.5194/tc-7-229-2013](https://doi.org/10.5194/tc-7-229-2013), 2013.

I have added a simple comparison script (compare_results.py) to the example which shows the differences between IGM, my SIA model and the exact reference surface of Ed Bueler's benchmark.

As you can see, IGM develops a preferential flow in certain directions already after a couple of hundred years. The ice dome, no matter if simulated with SIA or Full-Stokes, should remain circular symmetric however, as the model is driven with a circular symmetric SMB. My initial guess would be that the preferential flow directions in IGM stem from the CNN training datasets, which include valley glaciers with strong directional flow patterns based on the topography used. 

Looking forward to hear your comments and hope that benchmark is a useful addition to IGM. I would argue you should incorporate it as a standard test. Also happy to help research that property of IGM.

Kind regards,
Alex

### CODE REVIEW

**Comment by fmaussion** [comment]
Thanks @alexjarosch ! Because I'm too lazy to run the code ;-) could you paste a few of the plots you generated here to have a look?

The one thing that surprises me is that as of IGM v2 (https://doi.org/10.1017/jog.2023.73) the CNN is not trained on mountain glaciers or by any specific dataset anymore.

**Comment by alexjarosch** [comment]
Hi @fmaussion, sure, here is the IGM simulated surface after 600 years of evolution and the surface mass balance forcing at the same model time.
This is the IGM surface (t=600 years)
IGM_usurf_t600

and this is the SMB forcing (t=600 years)
SMB_t600

as you can see the forcing is circular symmetric, whereas the ice dome that IGM grows is not! Given the flat bed topography, this is not the behaviour expected. Model spatial resolution is dx=dy=100 m.

Thanks for the hint on the training of the IGM. However, you see the unexpected and incorrect behaviour with the setup as submitted. I just cloned the repo today and ran with the development version as is (last commit by Giullaume on Thu Jun 6 15:39:45 2024 +0200). The IGM config should be clear from the submitted params.json.

I am sure you are familiar with the Bueler C benchmark, but to summarize, it starts of with a flat, empty bed and then adds circular symmetric SMB fields that depend on model time. Thus the benchmark creates a growing (moving ice margin) circular ice dome for which (in case of SIA flow) an analytical shape function exists. Normally one would compare with that shape and worry about correctness of the margin position and central dome height. IGM however already struggles with creating a circular symmetric dome.

Kind regards,
Alex

**Comment by jouvetg** [comment]
Hi @alexjarosch , many thanks for submitting your test, that's great and very useful!
I quickly looked at the issue and the outcome is : I confirm the problem is clearly on the emulator side (as if you switch to the solver  "iflo_type": "solved"  this is perfectly symmetric). You used a pre-trained emulator, with little retraining, so that the ice flow field is biased by what it has seen at training. I could re-establish a decent symmetry by i) increasing the retraining frequency ("iflo_retrain_emulator_freq": 1, instead of 10), and also include a bit a sliding. This also show that the default retraining value is to be changed to a more conservative value in the next release. I must deepen why including a bit of sliding helps (I think I know why but must investigate). I'm happy to include your test, it would be good to push it entirely so that we can get to consistent shape with the analytical solution, and yours. However, one question: the SMB implementation is only positive, should not it be partly negative, otherwise, it will grow infinitely, and we will never get a steady shape? (that's what I get after fixing the symmetry issue by any solution solver or more intense retraining + slighlt sliding). All the best, Guillaume

**Comment by alexjarosch** [comment]
Hi @jouvetg, great to read that you find the benchmark useful and that you could already change the setup to make the ice dome radially symmetric. I think it is important to make it clear to the user with which setup this benchmark works, as you already indicate in your post.

Regarding the sliding, this benchmark (Bueler 2005 C) is specifically designed for a no-basal-sliding setup, so it is indeed worthwhile investigating why you require sliding. Bueler 2005 E includes linear sliding in a sector, should you be interested.

Regarding the positive mass balance. Yes, Bueler 2005 C is growing an ice dome and a time-dependent, positive mass balance is prescribes in each time step. Thus no steady shape is reached. However an exact solution for the dome shape is given in Bueler et al 2005 for each model time and so one can compare at any moment in time. The fun here is that it is a moving margin experiment and one can investigate the moving ice margin precision (numerics vs exact solution).

Bueler 2005 A and E do converge to a steady state and those could be implemented as well. However I personally find the Bueler 2005 C test the most interesting one as we normally (in the real world) never reach any steady states ;)

Have a great weekend, kind regards, Alex

**Comment by fmaussion** [comment]
Glad to read this!

This makes me wonder:
1. if the pre trained emulator shipped with IGM shouldn't rather be trained on a perfectly circular shape like this one, and 
2. what will the next default training frequency be?

**Pull request merged**
